### ISSUE TITLE
Bar does not update but append svg when changing the input

### ISSUE THREAD

**Issue by sakritz** [dreamRs/bar#2]
Let me start off by saying that I really love the simple elegance of these bar charts!

However, I'm having some trouble with dynamic inputs because the bar is not updated/replaced when changing the input but instead a second bar appears below the first one (and so on). 

Below is a simple reprex:

```{r}
library(shiny)
library(tidyverse)

ui <- fluidPage(
  fluidPage(
    selectInput("Input", label="choose", choices=c("mpg", "cyl")),
    fluidRow(barOutput("bar")
    )
  )
)

server <- function(input,output,session)({
  
  output$bar <- renderBar({
    
    dt <- mtcars %>% 
      add_rownames(var = "rowname") %>% 
      select(rowname, input$Input)
    cols = map(rev(colorRampPalette(c("#FFFFFF", "#000000"))(nrow(dt))), as.character())
    names(cols) <- dt$rowname

    bar(data = dt, colors = cols)
    
  })
})

shinyApp(ui = ui, server = server)
```

**Comment by pvictor** [comment]
Indeed, thanks for reporting it. Re-install from GitHub it should works, let me know.
All credits for these charts goes to [proportions-chart](https://github.com/vasturiano/proportions-chart) library !

Victor

**Comment by sakritz** [comment]
Works perfectly! Thanks for the quick fix!
